### ISSUE TITLE
Enhancement: export field data

### ISSUE THREAD

**Issue by MuellerSeb** [pyscience-projects/pyevtk#15]
None of the provided routines can handle field data.

[Meshio](https://github.com/nschloe/meshio) for example is capable of that, but there only structured meshes are supported.

It would be nice to also export ``field_data`` passed as a dictionary in the high-level routines.

Would it be possible with this low-level function to just create a field data section:
https://github.com/pyscience-projects/pyevtk/blob/90c7783bc7c4a825cae43ec4891dcb3408ba3bf4/pyevtk/vtk.py#L263
?

Cheers, Sebastian

**Comment by renefritze** [comment]
Sounds like a good enhancement that would be straightforward to implement. Would you be interested to post a PR for this @MuellerSeb ?

**Comment by MuellerSeb** [comment]
See #17
