### ISSUE TITLE
1.0.2 wheel for py3?

### ISSUE THREAD

**Issue by renemilk** [pyscience-projects/pyevtk#2]
Could you upload that to PyPi too, @somada141 ?

When I get around to adding more tests than just importing submodules, we could switch to deploying tagged builds to pypi from travis builds. It's pretty straightforward.

**Comment by somada141** [comment]
can do, can you bump the version? there's already a 1.0.2 release on PyPI (https://pypi.python.org/pypi/PyEVTK)

**Comment by somada141** [comment]
actuall nvm i'll do it, reckon this is a minor release so i'll bump it to 1.1.0

**Comment by somada141** [comment]
done

**Comment by renemilk** [comment]
Thanks, I'm only seeing the py2 version on https://pypi.python.org/pypi/PyEVTK though.

**Comment by somada141** [comment]
on it

**Comment by somada141** [comment]
that should do it

**Comment by renemilk** [comment]
And the source tarball too, thanks!
