### ISSUE TITLE
Update PyPI version

### ISSUE THREAD

**Issue by anicusan** [pyscience-projects/pyevtk#20]
Hello all, and thank you for creating such a helpful package - the only one really that doesn't need to pull in a whole `libvtk`. I would like to have a downstream Python library depend on `pyevtk`; however, the latest [PyPI version](https://pypi.org/project/pyevtk) is behind the latest [GitHub release](https://github.com/pyscience-projects/pyevtk/releases) and [conda version](https://anaconda.org/conda-forge/pyevtk) which are, in turn, 22 commits behind the master.

The last commits also add quite a few improvements that would be useful for downstream library developers (who publish their package to PyPI too). Would it be possible to update the PyPI version to 1.1.2 and perhaps publish the latest commits in a new release?

**Comment by renefritze** [comment]
Hey @anicusan, 
thank you for the interest in the package.
I'll try to fit a new release into my schedule for next week. Feel free to remind me if I forget.

**Comment by somada141** [comment]
Thanks for taking point once again @renefritze! Maybe adding CI/CD via GH actions would be a good idea here.

**Comment by renefritze** [comment]
> Maybe adding CI/CD via GH actions would be a good idea here.

Indeed. An action could also draft a GH release.
