### ISSUE TITLE
Cannot install from tarball

### ISSUE THREAD

**Issue by renefritze** [pyscience-projects/pyevtk#3]
I'm preparing a conda-forge recipe for pyevtk atm, since I want to use it in a conda package for pymor. Turns out the current tarball does not include the README.md, so setup.py from an sdist fails. I will fix this, add a check in CI and would then create a 1.1.1 tag. 

Sounds good, @somada141 ?

**Comment by renefritze** [comment]
I also want to switch the coverage provider from coverass to codecov.io. Coveralls looks basically unmaintained and their client now introduces a version conflict for ```coverage==4.0.3,>=4.4```

**Comment by somada141** [comment]
all good, I updated it.

**Comment by renefritze** [comment]
This is now fixed with #4 merged.
I've bumped the version + tag. Could you upload to pypi, @somada141 ?

**Comment by somada141** [comment]
@renefritze reckon you can update the README to point to this repo instead of the bitbucket one?

**Comment by somada141** [comment]
also I see the tag as 1.1.1. but the version reads 1.1.0 (https://github.com/pyscience-projects/pyevtk/blob/master/setup.py#L39) which is already on NumPy

**Comment by renefritze** [comment]
Apparently I forgot to push the tagged commit yesterday: https://github.com/pyscience-projects/pyevtk/commit/997800757c5ed07acbd07bc7c883fa8b52ba4151

Also updated the fork URL now.

**Comment by somada141** [comment]
uploaded to pypi
