### ISSUE TITLE
Stepping down as maintainer

### ISSUE THREAD

**Issue by renefritze** [pyscience-projects/pyevtk#38]
Due to leaving my position in academia, I will no longer have time to spend on this project going forward.
@somada141 @xylar 

If he's interested, I would nominate @MuellerSeb to replace me.

**Comment by MuellerSeb** [comment]
I guess there should be less redundancy in packages doing the same thing and people should join forces in maintenance:
- [pyevtk](https://github.com/pyscience-projects/pyevtk) (this): @somada141 @xylar (@MuellerSeb)
- [PyEVTK](https://github.com/paulo-herrera/PyEVTK) (origin): @paulo-herrera
- [uvw](https://github.com/prs513rosewood/uvw): @prs513rosewood
- [py2vtk](https://github.com/anlavandier/py2vtk): @anlavandier 

@renefritze thanks for your support of open source software and all the best for the future :upside_down_face: 

And for just clicking the release button, I could join this project.

**Comment by xylar** [comment]
@MuellerSeb regarding the redundancy, there's a long complicated history between this package and the original that you can read about in various places but the gist is that the original maintainer hasn't been particularly interested in maintaining a package that can be used on pypi or conda-forge so this version is what can be included in package management systems.  I also haven't had time to contribute much in many years but I think we've tried to bring over changes as they come in on https://github.com/paulo-herrera/PyEVTK.  As to the other 2, I'm not sure what the level of overlap might be.

**Comment by adamos-kyriakou-wolt** [comment]
@renefritze I appreciate the work you've put toward this especially as I just didn't have the time to devote to this project 🥰. I'd be happy for people that use this package semi-actively to maintain it though I couldn't ask anyone to do so when I simply can't commit any time to it.

**Comment by prs513rosewood** [comment]
Since I'm mentioned in this thread, I can give some context as to why uvw exists. I needed to be able to write VTK files with fields with an arbitrary number of components per data point, and pyevtk only supported 1 and 3 (from what I see that is still the case in both pyevtk repos). I made a PR (on bitbucket at the time) that added that feature and it was rejected by Paulo, so I wrote uvw, which uses Python's minidom to write XML and has an API closer to VTK file formats. I'd also like to point out that VTK now supports [HDF5 formats](https://examples.vtk.org/site/VTKFileFormats/#hdf-file-formats), so the need for specialized packages to write XML VTK files is likely to diminish, since HDF5 handles most of the features that the XML VTK format provides over the original format (compression, mpi-parallel io) and is much more widespread.

**Comment by paulo-herrera** [comment]
Dear All,

Thanks for including me in the discussion and your interest in EVTK.

As far as I know there is only 1 package (although the license allpws as
many forks as people want) that is distributed in different forms (which is
great). I imagine the wrappers (for pipy, conda, etc) around the package
can be done more or less automatically, but I prefer to not step on that.

Best regards,

Paulo

**Comment by renefritze** [comment]
> And for just clicking the release button, I could join this project.

That is basically the only thing I was doing after the initial automation setup anyways 😄 
It's pushing an annotated tag to the repo that triggers the release btw.

I'll add @MuellerSeb with Admin access then @xylar @adamos-kyriakou-wolt so he can do just that. And wiggle the branch protection after adding/removing python versions like in #36 .

**Comment by renefritze** [comment]
> I'll add @MuellerSeb with Admin access 

This is now done and I've also removed myself from that list. 

Thanks all!

**Comment by MuellerSeb** [comment]
@renefritze @xylar the invitation I got was invalid. Don't know why, but I can't get access to pyevtk. Could you re-invite me?

**Comment by xylar** [comment]
@MuellerSeb, I removed the old invitation and sent a new one.  Let me know if that works.  The issue may have been that @renefritze removed himself after sending the invitation but before you accepted it?

**Comment by MuellerSeb** [comment]
I also guess that this was the problem. Now it worked. Hello everyone :upside_down_face:
